### ISSUE TITLE
Scrolling issues when inside a container that overflows

### ISSUE THREAD

**Issue by tkoenig** [simonwep/selection#193] opened 2023-03-08 09:01 UTC
#### What is the problem?

I have a parent element of the selection area with the following style:

```css
  height: 100vh;
  overflow: auto;
```

#### What is the current behavior?

When scrolling, the selection area stays in the same position on screen, instead of also scrolling.

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).

https://codesandbox.io/p/sandbox/viselect-vanilla-forked-bjz7jz

#### What is the expected behavior?

The selection area should also scroll, when scrolling down the screen.

#### Your environment:
```
Toolset (e.g. webpack, vite, vue-cli...): esbuild
Version (@viselect/<insert package>): @viselect/vanilla@3.2.5
Browser:  Safari 16.3
OS:  MacOS Ventura
```

**Comment by Simonwep** [comment] 2023-04-11 16:12
Seems like this happens when the keys are used... will be fixed with the next patch release :)

**Comment by HollaG** [comment] 2023-05-16 13:08
Would like to pop in here and say I'm facing this issue with a horizontal scrolling container as well.

Using React version

**Comment by rlesniak** [comment] 2023-07-25 13:01
Hey @simonwep again! 😄 I decided to choose your library and here I am dealing with same issue. I have radix-ui scroll area, and inside it, I want to use your selectable, but cannot scroll while selecting 😞 any idea?

**Comment by simonwep** [comment] 2023-07-25 14:01
> Hey @simonwep again! smile I decided to choose your library and here I am dealing with same issue. I have radix-ui scroll area, and inside it, I want to use your selectable, but cannot scroll while selecting disappointed any idea?

Could you re-produce it on https://codesandbox.io? Maybe your case is a good starting point for me to fix it, this has always been a somewhat tricky issue

**Comment by rlesniak** [comment] 2023-07-25 14:18
Sure, here is exactly your code from demo, but in scroll area wrapper - https://stackblitz.com/edit/vitejs-vite-fdtdkl?file=src%2FApp.jsx

**Comment by rlesniak** [comment] 2023-07-26 09:42
Hey, @simonwep, I found solution. Working on PR right now

**Comment by simonwep** [comment] 2023-07-30 08:30
This seems to be a duplicate of #153, please move the discussion there. Maybe changing your boundary fixes it?

**Closed by simonwep** 2023-07-30 08:30 UTC
Labels: bug
