### ISSUE TITLE
Problem with scroll containers in Webkit browser

### ISSUE THREAD

**Issue by KKondratenya** [Simonwep/selection#143] opened 2021-11-04 11:56 UTC
#### What is the problem?

Area selection is moving from start position so it is imposible to select all wanted elements.

#### What is the current behavior?

In my own project the same problem happened with Firefox but in codesandox i reproduced this only in Webkit. The problem also mentioned in this [issue](https://github.com/Simonwep/selection/issues/140). 

https://user-images.githubusercontent.com/43761272/140308694-be28e51e-1902-4e9d-98f8-5400874e963d.mp4

#### What is the expected behavior?
All elements should be selected from start of selection to the end

#### Your environment:
```
Toolset (e.g. webpack, vite, vue-cli...): vite
Version ("@viselect/vanilla": "3.0.0-beta.11")
Browser:  Web Gnome WebKitGTK 2.32.0
OS:  Ubuntu 20.04
``
`

**Comment by Simonwep** [comment] 2021-11-16 10:59
Duplicate of #140

**Closed by Simonwep** 2021-11-16 10:59 UTC
Labels: unconfirmed
