### ISSUE TITLE
Single Tap

### ISSUE THREAD

**Issue by luizping** [Simonwep/selection#100] opened 2021-03-18 15:47 UTC
When we use singletap with CTRL, for example i select one element, CTRL+Click select a second element. All elements between these 2 elements are selected.
if not possible to select just these 2 elements?

**Comment by Simonwep** [comment] 2021-03-18 18:18
Just don't press `CTRL`? `CTRL` is used to select a _range_ of elements...

**Comment by luizping** [comment] 2021-03-18 19:41
Yes, but using your example, if I want to select 2 items, when I click the second, the first one unselect

**Comment by Simonwep** [comment] 2021-03-19 14:16
No wait - shift is used to select a range, ctrl is for single selection. What do you expect? You select one element, if you select another one _without_ pressing `ctrl` it'll de-select all the other ones but **if** you press `ctrl` it'll keep the previously selected one.

Btw, Please stick to the [Issue Template](https://github.com/Simonwep/pickr/tree/master/.github/ISSUE_TEMPLATE). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible. I'll close this issue if it stays unclear.

**Comment by Simonwep** [comment] 2021-04-16 13:24
Hey :) Duplicate of #106 - will be part of the release this weekend!

**Closed by Simonwep** 2021-04-16 13:24 UTC
Labels: question
